### ISSUE TITLE
Extract Pages to create other pdf

### ISSUE THREAD

**Issue by nazarhussain** [jonmagic/grim#26]
Hello, 

I have a scenario where I need to extract specific pages from pdf and create a pdf only from those pages. 

Can this library will be helpful in this scenario?

I will be thankful to your help.

**Comment by jonmagic** [comment]
> I have a scenario where I need to extract specific pages from pdf and create a pdf only from those pages.

Grim can extract specific pages but it extracts them as individual images. It does not have any functionality for creating a new pdf from those images.
