### ISSUE TITLE
ImageMagick processor changing white to black unnecessarily

### ISSUE THREAD

**Issue by rbrigden** [jonmagic/grim#28]
We are processing a high volume of documents with Grim and many of the documents white backgrounds become black when converted to JPGs. I believe the issue has to do with an [alpha layer in the PDFs](http://stackoverflow.com/questions/10934456/imagemagick-pdf-to-jpgs-sometimes-results-in-black-background). 

I tried to remedy the issue by adding an alpha flag. I used -alpha remove and -alpha flatten as such
`page.save path, width: 1024, quality: 70, density: 150, alpha:"remove"`
to no avail.

These flags do work, however, when using the standalone CLI imagemagick tool. 

Any help would be much appreciated.

**Comment by jdraths** [comment]
Bump I've got the same issue.

**Comment by frankzumut** [comment]
Help please, HI big Ron, I am tired of looking at dark pictures.  I tried the issue assist, but it didn't work.  Just give a clue,my brother. Tks.


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: BigRon <notifications@github.com> Date: 6/9/2016  07:07  (GMT-08:00) To: jonmagic/grim <grim@noreply.github.com> Subject: Re: [jonmagic/grim] ImageMagick processor changing white to black
  unnecessarily (#28) 
Bump I've got the same issue.

**Comment by frankzumut** [comment]
Here is an example,


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: BigRon <notifications@github.com> Date: 6/9/2016  07:07  (GMT-08:00) To: jonmagic/grim <grim@noreply.github.com> Subject: Re: [jonmagic/grim] ImageMagick processor changing white to black
  unnecessarily (#28) 
Bump I've got the same issue.

**Comment by jonmagic** [comment]
Can you try the version I've spiked in https://github.com/jonmagic/grim/pull/29 and give it a logger using the instructions provided there? Then when you extract a page from a pdf you should be able to see exactly how it ran the command and compare it to how you are running it manually.

**Comment by jonmagic** [comment]
Heh, I found ran into just this issue with a pdf I was using for testing https://github.com/jonmagic/grim/pull/29. Too tired to dig into it tonight though.

**Comment by jonmagic** [comment]
Tonight I did a little investigation using the new logging capabilities. First I extracted a page from a pdf that should be black text on a white background but ended up being [white text on a black background](http://cl.ly/2h1u2g1M1v45/2016-06-13%20at%2010.05%20PM.png).

```
irb(main):005:0> pdf[1].save("/Users/jonmagic/Downloads/black-on-white.jpeg")
D, [2016-06-13T21:59:28.346631 #14325] DEBUG -- Grim: Running imagemagick command
D, [2016-06-13T21:59:28.347589 #14325] DEBUG -- Grim: convert -resize 1024 -antialias -render -quality 90 -colorspace RGB -interlace none -density 300 /Users/jonmagic/Documents/olympus\ e-pl5\ manual.pdf[1] /Users/jonmagic/Downloads/black-on-white.jpeg
```

Then I ran that extraction again using the settings you mentioned in the body of this issue.

```
irb(main):006:0> pdf[1].save("/Users/jonmagic/Downloads/black-on-white-2.jpeg", width: 1024, quality: 70, density: 150, alpha:"remove")
D, [2016-06-13T22:00:50.488467 #14325] DEBUG -- Grim: Running imagemagick command
D, [2016-06-13T22:00:50.488550 #14325] DEBUG -- Grim: convert -resize 1024 -alpha remove -antialias -render -quality 70 -colorspace RGB -interlace none -density 150 /Users/jonmagic/Documents/olympus\ e-pl5\ manual.pdf[1] /Users/jonmagic/Downloads/black-on-white-2.jpeg
```

Using those settings appears to have fixed the problem I was having. The extracted page was now [black text on a white background](http://cl.ly/3x3W0U3I0y1p/2016-06-13%20at%2010.06%20PM.png).

**Comment by jdraths** [comment]
@jonmagic thanks for the work on this. I'll try this later today and let you know if I see anything different... Now to go to a meeting (brutal).

**Comment by jonmagic** [comment]
After merging the logging PR there are now instructions for connecting a logger in the [README](https://github.com/jonmagic/grim#usage).

**Comment by jdraths** [comment]
Worked great! Thanks.
