### ISSUE TITLE
Grim sample code not working

### ISSUE THREAD

**Issue by aliakbarpunathil** [jonmagic/grim#30]
Following error is thrown when run the  code

pdf = Grim.reap("pdf.pdf")
count = pdf.count
pdf[3].save('like.png')
text = pdf[3].text

pdf.each do |page|
  puts page.text
end

Error
[pdf.pdf](https://github.com/jonmagic/grim/files/692755/pdf.pdf)

C:/Ruby200/lib/ruby/gems/2.0.0/gems/grim-1.3.0/lib/grim/image_magick_processor.r
b:21:in ``': No such file or directory - gs -dNODISPLAY -q -sFile=pdf.pdf C:/Rub
y200/lib/ruby/gems/2.0.0/gems/grim-1.3.0/lib/pdf_info.ps (Errno::ENOENT)
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/grim-1.3.0/lib/grim/image_magic
k_processor.rb:21:in `count'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/grim-1.3.0/lib/grim/pdf.rb:35:i
n `count'
        from pdfpng.rb:18:in `<main>'

**Comment by jonmagic** [comment]
Please see the [usage instructions](https://github.com/jonmagic/grim#usage) for specifying the path to imagemagick and ghostscript.
