### ISSUE TITLE
Difference between quality and density?

### ISSUE THREAD

**Issue by kamok** [jonmagic/grim#38]
Is an image's quality not comprised of its pixel density and resolution?

What's the actual utility of the quality option?

**Comment by jonmagic** [comment]
> Is an image's quality not comprised of its pixel density and resolution?
> 
> What's the actual utility of the quality option?

Quality is inversely related to compression afaik. From https://en.wikipedia.org/wiki/JPEG:

> The degree of compression can be adjusted, allowing a selectable tradeoff between storage size and image quality.

Also see https://github.com/ImageMagick/ImageMagick/blob/a7e810e41cfc29c9c8e6eabb43ea0c52e26d0664/coders/png.c#L10699-L10736 for some notes on png compression.
