### ISSUE TITLE
File.exists? deprecated since Ruby 2.1.0

### ISSUE THREAD

**Issue by fgiannattasio** [jonmagic/grim#41]
Hi, 

As `File.exists?` has been deprecated since Ruby 2.1.0, would be nice to swith to` File.exist?` in lib/grim/pdf.rb

```
  1) Grim::Pdf should not raise NoMethodErrod for File:class
     Failure/Error:
       expect{
         pdf = Grim::Pdf.new(fixture_path("smoker.pdf"))
       }.not_to raise_error(NoMethodError)

       expected no NoMethodError, got #<NoMethodError: undefined method `exists?' for File:Class> with backtrace:
         # ./lib/grim/pdf.rb:18:in `initialize'
         # ./spec/lib/grim/pdf_spec.rb:8:in `new'
         # ./spec/lib/grim/pdf_spec.rb:8:in `block (3 levels) in <top (required)>'
         # ./spec/lib/grim/pdf_spec.rb:7:in `block (2 levels) in <top (required)>'
         # ./spec/lib/grim/pdf_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.01266 seconds (files took 0.11393 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/lib/grim/pdf_spec.rb:6 # Grim::Pdf should not raise NoMethodErrod for File:class
```

**Comment by cboulanger** [comment]
It can be worked with adding `class File; class << self; alias exists? exist?; end; end;` but a fix would be much better.

**Comment by cknoxrun** [comment]
Just ran into this today, I can through a quick PR together if PRs are still actively being merged?

**Comment by jonmagic** [comment]
Still accepting contributions 👍 I'm currently on vacation though so it will be end of next week before I can test the changes and do a release (added to my calendar so I don't forget).

In the meantime feel free to use this method to install the version from https://github.com/jonmagic/grim/pull/43 and see if it works for you.

Here are the bundler instructions for installing gems from a git repo: https://bundler.io/guides/git.html

**Comment by jonmagic** [comment]
@fgiannattasio thank you so much for your contribution! I added you as a contributor to the README and pushed the new version to rubygems.org ❤️ https://rubygems.org/gems/grim
