### ISSUE TITLE
need help w/ the gem

### ISSUE THREAD

**Issue by drhuffman12** [jonmagic/grim#42]
I added the `grim` gem (and just that gem) to my `Gemfile` and ran `bundle`; I got a long error; please help:

```
$ bundle
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
The git source `git://https://github.com/jonmagic/grim` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config set --local git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://https//github.com/jonmagic/grim
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
ArgumentError: Gem sources must be absolute. You provided 'https/'.
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/settings.rb:508:in `normalize_uri'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/settings.rb:490:in `key_for'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/settings.rb:304:in `key_for'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/settings.rb:98:in `[]'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/source/git/git_proxy.rb:201:in `configured_uri_for'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/source/git/git_proxy.rb:92:in `checkout'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/source/git.rb:326:in `fetch'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/source/git.rb:172:in `specs'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/source.rb:58:in `spec_names'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/source_map.rb:21:in `block in all_requirements'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/source_map.rb:20:in `map'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/source_map.rb:20:in `all_requirements'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/definition.rb:799:in `source_requirements'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/definition.rb:477:in `resolver'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/definition.rb:279:in `resolve'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/definition.rb:177:in `resolve_remotely!'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/installer.rb:271:in `resolve_if_needed'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/installer.rb:82:in `block in run'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/process_lock.rb:12:in `block in lock'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/process_lock.rb:9:in `open'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/process_lock.rb:9:in `lock'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/installer.rb:71:in `run'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/installer.rb:23:in `install'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli/install.rb:62:in `run'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:257:in `block in install'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:256:in `install'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:48:in `block in <top (required)>'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:36:in `<top (required)>'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `load'
  /home/drhuffman12/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.3.26
  Platforms   ruby, x86_64-linux
Ruby          3.1.3p185 (2022-11-24 revision 1a6b16756e0ba6b95ab71a441357ed5484e33498) [x86_64-linux]
  Full Path   /home/drhuffman12/.asdf/installs/ruby/3.1.3/bin/ruby
  Config Dir  /home/drhuffman12/.asdf/installs/ruby/3.1.3/etc
RubyGems      3.3.26
  Gem Home    /home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0
  Gem Path    /home/drhuffman12/.local/share/gem/ruby/3.1.0:/home/drhuffman12/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0
  User Home   /home/drhuffman12
  User Path   /home/drhuffman12/.local/share/gem/ruby/3.1.0
  Bin Dir     /home/drhuffman12/.asdf/installs/ruby/3.1.3/bin
OpenSSL       
  Compiled    OpenSSL 3.0.7 1 Nov 2022
  Loaded      OpenSSL 3.1.2 1 Aug 2023
  Cert File   /home/linuxbrew/.linuxbrew/etc/openssl@3/cert.pem
  Cert Dir    /home/linuxbrew/.linuxbrew/etc/openssl@3/certs
Tools         
  Git         2.34.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-09-10
Git SHA           unknown
Released Version  false
```

## Gemfile

### Gemfile

```ruby
# source "https://rubygems.org"


# gem "pdf-reader", "~> 2.2"
# gem "ascii85_native"
# gem install ascii85_native
gem 'grim', git: "git://https://github.com/jonmagic/grim"
```

### Gemfile.lock

```
<No /home/drhuffman12/_tmp_/github/drhuffman12/lotto_scanner/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Gem+sources+must+be+absolute.+You+provided+%27https%2F%27.&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
```

**Comment by jonmagic** [comment]
Howdy :) I think you need to uncomment this line in your Gemfile by removing the # at the beginning of the line:

`source "https://rubygems.org"`
